パーサーの仕様を変更
abap34/almo pull request #130
Opened 2024-05-26 10:08 UTC by noya2ruler

大量の仕様変更を行なっている；

大きめの変更

- パーサーが根ノードを定義して返す仕様から、引数で根ノードを与えてパーサーは `void` を返す仕様に変更
- `NonLeaf` と `Leaf` の区別を撤廃
- 複数行にわたるブロックのパースを補助する `Reader` クラスを作成
-  `Block` 構文と `Inline` 構文を定義、パーサーを関数オブジェクトとして提供させる仕様にした
- インライン記法はブロック記法を含まない限り先の行まで読み続けるべきなので、そのような仕様になるようパーサーの実装を変更

小さめの変更

- 保持する uuid を `int` に変更
- `Block::render` が担っていた機能を `to_html` が担うよう変更、`render` を削除
-  `InlineParser` はインスタンスを生成せずに文字列をパースできる仕様に変更
- ファイル終端の構文 `EOF` を追加、なお、これはASTには現れない
- `RawText` は特別にパーサーを持たず、 `InlineParser` が実質的なパーサーを担当する
- to_dot は根ノードかどうかのフラグを受け取る仕様から、呼び出し側が返り値の文字列を加工させる仕様に変更（ `render.hpp` の `md_to_dot` を参照のこと）

2024-05-26 10:22 UTC, abap34 requested changes
ありがとう！
ロジックのところは後でじっくりみます。これだけ先に修正お願いします

2024-05-26 10:22 UTC, abap34 commented on src/syntax/CodeBlock.hpp
> +struct CodeBlock_syntax : public BlockSyntax {
snake case と camel case が混在しているので、 `CodeBlockSyntax` とかにして欲しいです (ほかの syntax も)

2024-05-29 18:00 UTC, noya2ruler commented on src/syntax/CodeBlock.hpp
> +struct CodeBlock_syntax : public BlockSyntax {
7b56663 で修正しました。

2024-05-29 19:44 UTC, noya2ruler commented
すべての構文を定義し終えて、`example/example.md` は完全にパースできるようになりました。
- `bash scripts/setup.sh`
- `g++ -std=c++20 build/almo.cpp -o newalmo`
- `./newalmo example/example.md -o example.html`

とかで試せるはず。

2024-05-31 16:58 UTC, abap34 requested changes

2024-05-31 16:58 UTC, abap34 commented on src/syntax/CodeBlock.hpp
> +        std::string language = read.get_row().substr(3);
`rtrim` した方が良さそうな感じがします

2024-05-31 16:58 UTC, abap34 commented on src/syntax/DivBlock.hpp
> +        std::string title = read.get_row().substr(3);
`title` というより `class` が適切 ?

2024-05-31 16:58 UTC, abap34 commented on src/syntax/EnumerateBlock.hpp
> +                std::cerr << "Warning line " << read.row + 1 << " :" << std::endl;
前処理のコメント削除等でもとの行数と現在の行数が対応しているとは限らないので、行数表示は諦めて中身で位置を示す方が親切そうです。(例: `Warning near "....."`)

2024-05-31 16:58 UTC, abap34 commented on src/syntax/Item.hpp
> +// 数式ブロック. 内容はMathJaxでレンダリングされる. 内容は `math-block` というクラスが付与されたdivタグで囲まれる
ミス？

2024-05-31 16:58 UTC, abap34 commented on src/syntax/ListBlock.hpp
> +                std::cerr << "Warning line " << read.row + 1 << " :" << std::endl;
ここも同様に、内容で位置を示すのが良さそうです

2024-05-31 16:58 UTC, abap34 commented on src/syntax/LoadLib.hpp
> +        if (rtrim(read.get_row()) == ":::lib") return true;
パッケージロードは

```
:::loadlib
numpy
matplotlib
:::
```

なのでそれでお願いします

```suggestion
        if (rtrim(read.get_row()) == ":::loadlib") return true;
```

2024-05-31 16:58 UTC, abap34 commented on src/syntax/Table.hpp
> +            }
ここの左右寄せ判定を、可能ならスペースを許容できるようにして欲しいです
(`| :--- | :---: | ---: |` が許容されてほしい)

2024-06-04 09:00 UTC, noya2ruler commented on src/syntax/EnumerateBlock.hpp
> +                std::cerr << "Warning line " << read.row + 1 << " :" << std::endl;
マルチバイト文字列に対応する処理が難しく、実装に悩んでいます。文字コードが分からないと直近 `n` 文字を取得などが正確にできない可能性があります。

2024-06-04 09:30 UTC, noya2ruler commented on src/interfaces/parse.hpp
> +};
9197f09aec8078fa47a231143ed381f0d17a6af3

2024-06-04 09:31 UTC, noya2ruler commented on src/reader.hpp
> +                std::cerr << "pyodide is required" << std::endl;
b1d053e40eedfcfbdc1cfb34ae75f1b06edafb64

2024-06-04 09:31 UTC, noya2ruler commented on src/syntax/InlineImage.hpp
> +        std::string caption = sm.format("$3");
83834d0921a9b83948bc95e51db1e9a6762c7b3d

2024-06-04 09:31 UTC, noya2ruler commented on src/syntax/InlineUrl.hpp
> +        std::string alt = sm.format("$3");
142e01f3e31dee95944153d676fb0758fdf6e92d

2024-06-04 09:32 UTC, noya2ruler commented on src/syntax/CodeBlock.hpp
> +        std::string language = read.get_row().substr(3);
2fc7852b948ab2d11906d9a938b7218a817945b8

2024-06-04 09:32 UTC, noya2ruler commented on src/syntax/DivBlock.hpp
> +        std::string title = read.get_row().substr(3);
23d3ebbd0240eed4a7ccd14b21e420fcfcb0930a

2024-06-04 09:34 UTC, noya2ruler commented on src/syntax/EnumerateBlock.hpp
> +                std::cerr << "Warning line " << read.row + 1 << " :" << std::endl;
05bcd97a88b6760f5bbfd92e4fa42a8dd71b451f

とりあえず直前の行があればそれをすべて、それと、今の行のこれまで読んだ部分を取得できるような関数を `reader` に用意しました。

2024-06-04 09:34 UTC, noya2ruler commented on src/syntax/Item.hpp
> +// 数式ブロック. 内容はMathJaxでレンダリングされる. 内容は `math-block` というクラスが付与されたdivタグで囲まれる
e35cd43842eaca4cdb67155869b7b80add242549

2024-06-04 09:34 UTC, noya2ruler commented on src/syntax/ListBlock.hpp
> +                std::cerr << "Warning line " << read.row + 1 << " :" << std::endl;
05bcd97a88b6760f5bbfd92e4fa42a8dd71b451f

2024-06-04 09:38 UTC, noya2ruler commented on src/syntax/Table.hpp
> +            }
84f41d0fe759439d5cb3792114a1823b27718608

これまでは先頭と末尾しか見ない実装になっていたため、正確でないフォーマット指定子も読むようになっていた。正規表現で正確なフォーマット指定を要求するように変更された。 

`:---:` などの `:` と `-` の間に空白 `\s*` が入ることを許容していないですが、許容した方が良いですか？

2024-06-04 09:53 UTC, abap34 commented on src/syntax/Table.hpp
> +            }
そこは許容しなくて大丈夫そうです。この実装で良さそうです。

2024-06-04 10:25 UTC, abap34 commented on src/syntax/EnumerateBlock.hpp
> +                std::cerr << "Warning line " << read.row + 1 << " :" << std::endl;
現在行の取得を読んだところまでにしてると思うんですが、現在行を全て取得した方が親切なメッセージが出せそうです。

https://github.com/abap34/almo/blob/05bcd97a88b6760f5bbfd92e4fa42a8dd71b451f/src/reader.hpp#L76

例えば

```
### 好きな食べ物

- ハンバーグ
- お寿司
- ピザ
 - ただしチーズはのせない
  - トマトは苦手 
```

をパースすると、

```
Warning near '- ピザ
'
indent width must be 2. this line is considered as raw text.
```

と出てきて実際インデントがスペース1つでおかしい `ただしチーズはのせない` が出てこず、混乱しそうです。

単に現在読んでる行は全て追加してまとめて出力するようにすると、

```diff
--- a/src/reader.hpp
+++ b/src/reader.hpp
@@ -73,7 +73,7 @@ struct Reader {
         if (row > 0){
             ret += lines[row-1] + "\n";
         }
-        ret += lines[row].substr(0,col);
+        ret += lines[row];
         return ret;
     }
 };
```

```diff
--- a/src/syntax/ListBlock.hpp
+++ b/src/syntax/ListBlock.hpp
@@ -111,7 +111,7 @@ struct ListBlockSyntax : public BlockSyntax {
                 // depth has decreased and the difference is even
                 if (depth < current && (current - depth) % 2 == 0) return true;
                 // ambiguous list definition detected
-                std::cerr << "Warning near '" << read.near() << "'" << std::endl;
+                std::cerr << "Warning: \n ... \n" << read.near() << "\n^^^ reading line" << std::endl;
                 std::cerr << "indent width must be 2. this line is considered as raw text." << std::endl;
                 return false;
             }()){
```


```
Warning:
 ...
- ピザ
 - ただしチーズはのせない
^^^ reading line
indent width must be 2. this line is considered as raw text.
```

という感じの出力になり、より明確になりそうです.

2024-06-04 10:41 UTC, noya2ruler commented on src/syntax/EnumerateBlock.hpp
> +                std::cerr << "Warning line " << read.row + 1 << " :" << std::endl;
7007d21135dd98d1da6a50de4fa88706590eb211

警告の種類を表示するようにした。（後々はワーニングのハンドラも作った方が良さそう。）

それと、 `reading` は主語がよく分からない気がするから `parsing` にしておいた。

2024-06-04 10:43 UTC, abap34 commented on src/syntax/EnumerateBlock.hpp
> +                std::cerr << "Warning line " << read.row + 1 << " :" << std::endl;
チェックしました。良さそうです！

2024-06-04 10:43 UTC, abap34 approved these changes

2024-06-04 10:44 UTC, abap34 commented
良さそうです。お疲れ様でした！ :tada:

2024-06-04 10:45 UTC, merged